services:
  bot:
    # image: stefdp/discord-user-apps
    ports:
      - 3000:3000
    build: .
    container_name: discord-user-apps
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/bot/data
      - ./permissions:/bot/src/data/permissions
